apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: vote
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= #postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM= #postgres
  
  #to generate the encrypted password. In reality base 64 encrytion is not preferred since its weak. 
  #echo "postgres" | base-64
