apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  type: NodePort
  ports:
    - name: "vote-service"
      port: 5000
      protocol: TCP
      targetPort: 80
      nodePort: 31002
  selector:
    app: vote
