apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  type: NodePort
  ports:
    - name: "result-service"
      port: 5001
      protocol: TCP
      targetPort: 80
      nodePort: 31003
  selector:
    app: result
